### ISSUE TITLE
ნიკი

### ISSUE THREAD

**Issue by DavidDeme** [SabaTD/Gym#1]
ნიკი შეიცვალე და რამე წესიერი დაიწერე. მაგ: SabaTandashvili ან SabaT. პლიუს ავატარიც დაიყენე :)

**Comment by SabaTD** [comment]
Done

**Comment by DavidDeme** [comment]
@SabaTD 
ავატარი ? :)

**Comment by SabaTD** [comment]
ავატარიც შეიცვალა :P

**Comment by DavidDeme** [comment]
:+1:
