### ISSUE TITLE
ტემპი

### ISSUE THREAD

**Issue by DavidDeme** [SabaTD/Gym#2]
ველოდები ატვირთულ კოდს და შეკითხვებს :)

**Comment by SabaTD** [comment]
ვერ ვტვირთავ წამეშალა

**Comment by DavidDeme** [comment]
@SabaTD 
1) ფაილს აგდებ GYM ფოლდერის რომელიმე სუბ-ფოლდერში. 
2) ხსნი გიტის დესკტოპ აპლიკაციას
3) გიჩვენებს რომ ცვლილებებია 
4) აწერ სათაურს და აღწერას. ორივე უნდა იყოს გამართული ინგლისურით დაწერილი და იწყებოდეს დიდი ასოებით. იყენებ ტეგებსაც #NewFile #FirstProject #InitialDocuments
5) აჭერ ღილაკს "Commit"
6) "Commit"-ს შემდეგ გინდა რომ ეგ ყველაფერი აისახოს ჰოსტზეც ანუ ამ საიტზე და აჭერ ღილაკს "Sync" ან "Publish" თუ პირველი ფაილებია. 
7) შენი GYM ფოლდერის ზუსტი ასლი ჩნდება სერვერზეც.

პს აქ ვწერთ ოფიციალური მიმართვებით. ჩატი არაა, მხოლოდ კითხვა - პასუხის რეჟიმი :)

**Comment by SabaTD** [comment]
გავეკეთე ბატონო დემე გაიხარეთ ;)

პროგრამა დაუსრულებელია დღეს საღამოს იქნება ბოლომდე მზად მანამდე კი ნაწილობრივ მუშაობს ბაზის გარეშე. 

პ.ს.   xampp-ის ბაზასა და  microsoft datbase-ს ბაზებს შორის რაიმე აზრი აქვს ჩემს შემთხვევაში რომელს გავაკეთებ ?

**Comment by DavidDeme** [comment]
@SabaTD კარგია. ბაზებს რაც შეეხება არსებითად არანაირი მნიშვნელობა არ აქვს, მითუმეტეს PDO-ს იყენებთ თურმე :). მოკლედ თუ რამე კითხვები გექნება გამოუშვი.

**Comment by SabaTD** [comment]
php კოდი დავწერე ბაზების  + ბაზიდან წაკითხვის, მაგრამ ბაზა ვერ გავაკეთე, კი შევქმენი microsoft acces database მაგრამ ცვლილებებს არ ასახავდა და  xampp ის ბაზა რო გავაკეთე მანდ ვერც ვნახე ცვლილებები.  არადა კოდი მგონი სწორი არაფერი ერორი არ გამოაქ. გადახედე რა რო მოიცლი და შეკითხვებსაც ჩამოვწერ რაც ვერ გავიგე.

**Comment by DavidDeme** [comment]
@SabaTD 
1) xampp-ს ბაზს რას უძახი, xampp-დან რომ mysql ადმინში შედიხარ ? 
2) თუ მაგას უძახი:
$conn = new PDO('mysql:host=127.0.0.1; dbname=sqllab' , "root", "");
mysql:host -> localhost, 
dbname -> რასაც დაარქმევ, 
ბოლო ორი სწორია.
3) ყოველ ახალ კითხვაზე ახალი Issue გააკეთე, ეს Issue სხვა რაღაცისთვის იყო გამიზნული.
