### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by SabaTD** [SabaTD/Gym#3]
1) xampp-ს ბაზს რას უძახი, xampp-დან რომ mysql ადმინში შედიხარ ? 
2) თუ მაგას უძახი:
$conn = new PDO('mysql:host=127.0.0.1; dbname=sqllab' , "root", "");
mysql:host -> localhost, 
dbname -> რასაც დაარქმევ, 
ბოლო ორი სწორია.

///////////////////////////////////////////////////////////////////////////////////////////////////////
mysql:host -> localhost, 
dbname->sqllab;

ასე მიწერია და ერორს აგდებს  mysql.php და  select.tphp ორივეგან, ავტვირთე განახლებული კოდი,  ესაა შეცდომა, '->'წავუშალე და რათქმაუნდა ვაფშე აირია. 

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in C:\xampp\htdocs\Gym\ProjectThree\pdo\mysql.php on line 8

**Comment by DavidDeme** [comment]
@SabaTD 
ქვემოთ რომ მაქვს -> ნიშნავს რომ იმის ადგილას უნდა ყოფილიყო. ესე დაწერე და ის ქვედა მიაშალე.
$conn = new PDO('mysql:host=localhost; dbname=sqllab' , "root", "");
მიხვდი ? 

რომ გიწერ mysql:host -> localhost ნიშნავს რომ ეს უნდა უდრიდესთქო, კოდში არ უნდა გადაგეტანა, მაგრამ არაუშავს, გაასწორე და მომწერე პასუხი :)

**Comment by SabaTD** [comment]
შევცვალე ორივეგან, ერორი აღარ გამოაქვს, შეიძლება მუშაობს მაგრამ ვერ ვნახულობ ბაზაში დამატებულ მონაცემებეს, ასეთი სიტუაციაა ახლა ბაზაში და რა ვქნა  ? 

http://prntscr.com/9iab2p

**Comment by DavidDeme** [comment]
@SabaTD 
დაამატე ბაზაში ჩანაწერები, მაქ ზემოთ Insert-ს დააჭირე.

**Comment by SabaTD** [comment]
http://prntscr.com/9idmj3

აქ რეები ავირჩიო არ ვიცი საერთოდ,  ბაზების კურსი ცალკე უნდა გავიარო ახლა ესენი რო გავარკვიო რაღაც ვიდეობი კი არის იუთუბზე მარა კოდითააქვთ შექმნილი ბაზები სულ და ვერ გავარკვიე რა უნდა ვქნა.
