### ISSUE TITLE
Can't Connect To The Database - ProjectFour

### ISSUE THREAD

**Issue by SabaTD** [SabaTD/Gym#4]
მომეხმარე რა ერთხელ დამაკავშირებინე ბაზასთან  php ფაილი რო შემდეგში მქონდეს მაგალითისთვის მესამე პროექტია უკვე ვერ ვაკავშირებ ბაზასთან დალშე სწორადმაქ კოდი რა გაგიხდა.

**Comment by DavidDeme** [comment]
@SabaTD 
რას ნიშნავს ვერ აკავშირებ.
1) შეცდომები გამოაქვს ?
2) თუ გამოაქვს ან აქ რატომ არ წერ ან რატომ არ ძებნი გუგლში
3) არასწორად წერ, მაქ ფუნქციები გიწერია რომელთა უმრავლესობაც რეალურად არ გესმის დარწმუნებული ვარ და აკოპირებ ლექტორისგან. შედეგად, არ შეგიძლია მიხვდე რაშია პრობლემა
მაგ: try - catch ბლოკები, include - require და რაღაცეები მომხვდა თვალში, თუნდაც SESSION. ასე რომ  შენითვე უნდა ჩაუჯდე და გაარკვიო რა, რისთვისაა და ა.შ. PHP xampp-ს ან git-ს დაყენება არ არის რომ ერთხელ გასწავლო, დღეში 24/7-ზე უნდა წერო და ასწორო შეცდომები. თან შენც იცი რომ არსებობს დამწყებისთვის მშვენიერი დოკუმენტაცია w3school-ზე და დეტალურადაა იქ ახსნილი ბაზასთან დაკონექტება და სხვა ბევრი რამ დამწყებისთვის გასაგებ ენაზე.
4) უკვე მემილიარდედ გიხსნი :)

**Comment by DavidDeme** [comment]
@SabaTD 
მოეშვი პირდაპირ ამ სირთულის კოდთან ჭიდაობას, გაიმარტივე საქმე.
მაგ:
1) შექმენი HTML დოკუმენტი რომელშიც შექმნი ფორმას და შეგეძლება მისი გაგზავნა მეორე ფაილისკენ, რომელსაც დაარქმევ server.php-ს
2) server.php-ზე უნდა შეგეძლოს ამ ფორმიდან გაგზავნილი ინფორმაციის წაკითხვა და დამახსოვრება
3) იქვე დაუკავშირდი ბაზას და შეიყვანე დამახსოვრებული მონაცემები
4) იმისათვის რომ ბაზაში რამე დაამატო, ჯერ უნდა არსებობდეს ბაზა და შემდეგ უკვე ცალკეული თეიბლი ამ ბაზაში, თავისი Column-ებით.
5) დაემატა თუ არა მაგას შეამოწმებ ისევ და ისევ ბაზაში. ასევე, ნებისმიერ შეცდომას ამოგიგდებს server.php-ზევე. 
6) კოდის წერისას თითოეულ გაურკვეველ დეტალს ძებნი გუგლში და ა.შ

**Comment by DavidDeme** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/4215681/12043251/d4ee5622-ae9c-11e5-9d8e-d4fd095d7e41.png)

ბაზასთან დაკავშირების და ინფორმაციის შეტანის კოდი.

**Comment by SabaTD** [comment]
კაროჩე გავაკეთებ მაგას რაც მეორე პოსტში დაწერე,  და  xampp-ის MYSQLS ადმინიდან რო გადავდივარ და მანდ ვქმნი ბაზას, მერე მანდვე   tables ვაკეთებ  მაგას ვერ მივაერთებ php ფაილს ? ანუ მზა ბაზა xampp-ს-ში  რო შეუერთდეს და არა შენ როგორც გიწერია მესამე პოსტში.

**Comment by DavidDeme** [comment]
@SabaTD 
1) ქმნი ბაზას
2) ქმნი თეიბლს თავისი Column-ებით, Id, Date, ...
3) უკავშირდები მაგ ბაზას PHP-ს დახმარებით, გამოიყენე მესამე პოსტში ჩაგდებული კოდი

მესამე კოდში რა წერია:
1) ზემოთ იწყებ იმით რომ სხვადასხვა ცვლადებში ინახავ ბაზის სახელს, ბაზის იუზერს, ბაზის იუზერის პაროლს და იმ ჰოსტის მისამართს რომელზეცაა გაშვებული ბაზა. ეგ ინფორმაცია შეიძლება შეიცვალოს, შენვე განსაზაღვრავ მაგას. რადგან ხშირ შემთხვევაში ბაზა და PHP ფაილები ერთ სერვერზეა ხოლმე ანუ ერთ კომპიუტერზე, მარტივი გზაა რომ IP მისამართის მაგივრად (196.168.1.1) დაწერო "localhost" და მერე უკვე ავტომატურად, შენგან დამოუკიდებლად უკავშირდება პროგრამა ლოკალურ მისამართს. შეგიძლია ექსპერიმენტი ჩაატარო და localhost-ს მაგივრად შენი კომპიუტერის IP მისამართი ჩაწერო, შედეგი იგივე იქნება.
2) mysqli_connect ფუნქციით ამყარებ კავშირს ბაზასთან და მაგ კავშირს (რესურსს) ინახავ ცვლად $con-ში
3) მერე მიდის გადამოწმება, თუ $con არ არსებობს ამოგიგდებს შეცდომას
4) წერ SQL ბრძანებას რომელმაც მაგ ბაზის თეიბლში ჩანაწერი უნდა დაამატოს
5) mysqli_query ფუნქციას გადასცემ $con ცვლადს რითაც ხვდება რომელ ბაზას დაუკავშირდეს და SQL ბრძანებას რომლითაც ხვდება რა უნდა გააკეთოს. if/else ბლოკით ამოწმებ იმ მხრივ რომ თუ რამე შეცდომაა დაგიწეროს. შეგიძლია ეგ ამოიღო და პირდაპირ mysqli_query($con, $sql) დაწერო და ის if/else ბლოკი ამოიღო
6) ხურავ ბაზასთან კავშირს.

**Comment by DavidDeme** [comment]
@SabaTD 
xampp-ს აქვს PHPMyAdmin მოდული სადაც გამარტივებულია ეგ ყველაფერი. ბაზასაც ქმნი, თეიბლსაც და ყველაფერს რაც საჭიროა.

**Comment by SabaTD** [comment]
ხო და რაც შეეხება არასწორად წერო სწორია მანდ ყველაფერი , ერორიც გამოქონდა ყველაფერზე , ბაზა xampp-ით გავაკეთე მაგრამ ვერ დავაკავშირე,  იმ როჟას ვინც ხსნის მაქბუქი აქ და რაგაც პროგრამაში წერს ჯერ და მერე  xampp-ის ბაზაში გადადის.  იუთუბზე რაც ვიდეოგაკვეთილები ვნახე  ყველგან კოდით აკავშირებენ და მასე არ მაწყობდა მაგიტო ვერ ვაკეთებ. ისე კოდი გამართულია იყო შეცდმოები რო მოვრჩი გამოქონდა კიდეც ერორები და შევასწორე,  რაც შეეხება გაგებას ხსნის და მესმის ელემენტარული რა რისთვისაა რო მკითხოს ვინმემ ავხსნი კომენტარებიც მიწერია ზოგიერთ რამეზე რაც ახალია უმეტესობა ProjectThree-შიც ახსნა სადაც ანალოგიურად ვერ დავაკავშირე ბაზასთან.

**Comment by DavidDeme** [comment]
@SabaTD 
ეს გაიგე ახლა რაც აგიხსენი ?.

**Comment by SabaTD** [comment]
რა  გამარტივებული მოდული გინდა 
http://prntscr.com/9k8jf1

აგერ მაქ გაკეთებული მთელი ბაზა,  

http://prntscr.com/9k8jms

ესეც ჩამატებულიმაქ იუზერი მაილი და პაროლი რო შემყავს login.php-ში რეაქცია უნდა ქონდეს მარა არაფერს შვება

**Comment by DavidDeme** [comment]
@SabaTD 
ცალკე ბაზა გააკეთეთქო, გაანებე მაგას თავი.
ორი ველი რომ იყოს და ნახო ჩაწერას თუ აკეთებ კოდიდან.
მაგ სირთულეებზე მერე ივარჯიშე შენით.

**Comment by SabaTD** [comment]
გავიგე იქ რაც ახსენი, გავაკეთებ მაგას ელემენტარულია თეორიულად პრაკტიკულად არ მიცდია ვიზავ ახლავე.

**Comment by DavidDeme** [comment]
@SabaTD 
ხოდა ელემენტარული თუა გააკეთე და დამიდე აქ კოდი. 
თეორიულად ;დ

**Comment by SabaTD** [comment]
http://prntscr.com/9k90ky

რა უდნა სმნ ?  კოდი ავტვირთე და ნახე რავი. კი ვნახე გუგლში მარა სხვანაირად აკეთებენ აშკარად და არ მინდა გადმოკოპირება ამ ხერხით როგორ გავაკეთო ?

**Comment by SabaTD** [comment]
http://prntscr.com/9k9a47

ესეც ბაზის სქრინი
