### ISSUE TITLE
Select Data From Database

### ISSUE THREAD

**Issue by DavidDeme** [SabaTD/Gym#5]
![screenshot_1](https://cloud.githubusercontent.com/assets/4215681/12097202/bccdf700-b333-11e5-8a8e-0db1396af928.png)

იყენებ ამ კოდს ბაზიდან მონაცემების ამოსაღებად

**Comment by SabaTD** [comment]
Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in C:\xampp\htdocs\Gym\ProjectFive\form.php on line 24
0 results

კოდი ავტვირთე შეხედე აბა თითქოს სწორადმაქვს მარა  მაინც რაღაც უნდა მივუგლავ მეც პარალელურად მარა  უშედეგოდ ალბათ.

**Comment by SabaTD** [comment]
იგივე შეცდომაა ბატონო დემე იქნება დამეხმაროთ ამ საღამოსაც
