### ISSUE TITLE
Project Progress - ToDoList

### ISSUE THREAD

**Issue by SabaTD** [SabaTD/Gym#6]
მოკლედ ცოტა დავხვეწე კოდი,  ბაზაში  id ის მინიჭება გავხადე ავტომატური,   ახლა ვცდილობ  აფდეითი გავაკეთო ისე რო დაკლიკვის დროს წამოიღოს ბაზიდან ფორმის ველებში ჩაწეროს ის ინფორმაცია რაზეც დავაკლიკე და რომ შევცვლი და submit მივცემ ისევ შეინახოს.  

გადახედე კოდს რა რო მიცლი რამე შენიშვნა თუ გაქვს მითხარი გავითვალისწინებ. 
ეს  delete სათითაოდ ექნება  ყველა პოსტს და id ის მიხედვით მიენიჭება ყველას რომელ პოსტზეა მიბმული რო მიხვდნენ  რავი ნორმალური იდეაა მგონი თუ სხვანაირადაც შეიძლება მითხარი მეტი ვერ მოვიფიქრე. 

 css-ით გავასწორებ მერე.

**Comment by DavidDeme** [comment]
@SabaTD 
განახლება/წაშლის შემთხვევაში იდეა არის მარტივი.
1) როცა საწყის გვერდზე იღებ ყველა ჩანაწერს, განახლება/წაშლის ღილაკებს უნდა მიაბა ID. ანუ პირველ გვერდზე დაახლოებით ესე უნდა წამოიღო -> [ჩანაწერი] [Edit ჩანაწერიID] [Delete ჩანაწერიID].
2) ID-ს საშუალებით შენ იდენტიფიცირებას უკეთებ უნიკალურ ჩანაწერს ბაზაში.
3) როცა ეგ ჩანაწერი იცი, მარტივია მისი ამოღება, ფორმაში ჩაგდება და ისევ განახლება, ანუ ამოღებული ჩანაწერის შეცვლა და გაგზავნა ბაზისკენ.
4) წაშლაზე პირდაპირ უნდა გაკეთდეს, გადავიდეს Delete გვერდზე, წაშალოს და დაბრუნდეს უკან.

კოდის გადახედვას აზრი არ აქვს, მთავარია პირველ რიგში ეგ სქემა აამუშავო და თვითონ ხარისხი, სტილი მერე გამოასწორო. ამიტომ თუ ამ სტილით კეთებისას რამე ერორი ამოგიგდო დამისქრინე. თუ იმუშავა, რასაც მე უკვე ლოკალურად შევამოწმებ ;დ, ნიშნავს რომ ეს დავალება შესრულებულია და მომდევნო დავალებებში ვიზრუნოთ უშუალოდ კოდის ხარისხზე.

**Comment by SabaTD** [comment]
ID- ებით გადავაბი წაშლაც და განახლებაც,   კაი ხნის ჩალიჩის მერე როგორც იქნა თარიღის დამატებაც დავამუღამე ბაზაში.  ასევე განახლების ფუნქციაც მუშაობს სრულყოფილად ნებისმიერ  მონაცემს ID-ის მიხედვით ცვლის და იმავე ID-ის მონაცემებს გადააწერს ახლად შეტანილ მონაცემებს, ასევე თარიღსაც,  წაშლა ვერ გავმართე ბოლომდე რაღაც პატარა შეცდმა მაქვს და ვერ ვხვდები ჯერ.  

შეტანის ველები  bootstrap-ით   გავასწორე  რა მინიმალურ დონეზე.
მოფიქრებული ამქვს ეს გამოტანაც როგორ გავაკეთო css-ით ვიზუალურად, კოდში კი რა გითხრა php   კოდზე ჯერ  დამიწერია css ეხლა მიწევს პირველად.

**Comment by SabaTD** [comment]
მოკლედ მოვრჩი ამას, ვიზუალურადაც გავმართე და წაშლის ფუნქციაც დავამატე , რავიცი მოკლედ თან ყველა მონიტორზე რო კაი იყოს ისე ვქენი  ცოტა შესწორება უდნა კიდე მარა წავა რა, იქ 22 იანზე ვწერე კოლეჯში და ჩემთან ახლა 17 იანზე ცოტა მარჯვნივაა გაწეული დალშე ნორმ.

რავი გადახედე განვიხილოთ და ახალი დავალებაც მინდა.
