### ISSUE TITLE
Project Evaluation - ToDoList

### ISSUE THREAD

**Issue by DavidDeme** [SabaTD/Gym#7]
მოკლედ გადავხედე ერთ-ერთ ფაილს და გაგისწორე შეცდომები, კომენტარებიც დავუწერე. გადახედე ამ ფაილს, კარგად გაიაზრე და ამის მიხედვით გაასწორე სხვა შეცდომებიც. სანამ ეს შეცდომები არ გასწორდება პროექტი არ ჩაითვლება. ვიზუალი არ შემიმოწმებია ანუ დიზაინის მხარე, მაგას უკვე ბოლოსკენ ვნახავ და მაგასაც გავასწორებ.
რაც თვალში მომხვდა და არ მომეწონა
1) უაზროდ აცხადებ ცვლადებს. მაგ: ზემოთ გქონდა ჩამოწერილი ბაზის ინფორმაცია და არც იყენებდი, ფუნქცია გქონდა სადაც პირდაპირ წერდი მაგ მონაცემებს.
2) იყენებ მოძველებულ mysql ფუნქციებს, როცა უნდა იყენებდე mysqli-ს. განსხვავება თუ გაინტერესებს დაგუგლე. ვინც მაგ ძველი ფუნქციებით დაგაწერინებს არ დაუჯერო, არ ჩაიწერო.
3) კოდში იყენებ ქართულ დასახელებებს. გამოიყენე ინგლისური. მაგ: $shedegi-ს მაგივრად $result. 
4) არ იცავ კოდის დაწერის პრინციპებს. როგორც PHP-ში ისე HTML-ში, ანუ ტაბის ჩარტყმა რომ საჭიროა. 
5) როცა SQL ბრძანებას წერ, გამოიყენე ეს სიმბოლო -> `, დაწერე SQL-ს სიტყვები დიდი ასოებით და "SELECT FROM WHERE".
6) მახინჯი კოდის მაგალით $title=$_POST["Title"]. უნდა გქონდეს -> $title = $_POST["Title"].

ჯერ-ჯერობით ესენია. ძველი ISSUE-ები დახურე, ამაში მომწერე დანარჩენი. სხვა ფაილებიც გაასწორე იმ ჩასწორებული ფაილის მიხედვით და სანამ ჩაასწორებ გაიაზრე რა და როგორ არის, რისთვის და ა.შ. სხვას მერე გადავხედავ თუმცა ძირითადად ეს შეცდომებია

**Comment by SabaTD** [comment]
გავითვალისწინებ მაგრამ აქ ბევრი რამე ზედმეტი რო მიწერია ეგ იმიტომ რომ არ ვიცოდი როგორ უნდოდა ასნაირად რო ვცადე ერთ-ერთი გამვოიდა ნახევარი კომენტარებში მაქ  რასაც ვცდილობდი და ასე შემდეგ, ქართულ სახელებს გამოვასწორებ.  და mysqli ვიყენებდი ამრა რაღაც მომენტს ვერ გავცდი და ლექტორი დავიხმარე და იმან არ ვიცი ეს mysqli ვაფშეო და i  მომაშლევინა :დ  ერთ ფაილშია მარტო მგონი ეგ დანარჩენი ყველგან  mysqli არის.   ტაბის ჩარტყმა არ შემეშლებოდა მე მაბრალებ რაღაცას -_- , ახლა ვნახე php-ში სად ჩაარტყი ტაბები მანდ გავითვალისწინებ მაშინ არ ვიცოდი თუ უნდოდა მანდ.   ეს მე-5 პუნქტი შენით რო დაგეწერა კე მივხვდებოდი წესივრად როგორ უნდა.   მე-6 საც გავითვალისწინებ :პ

**Comment by DavidDeme** [comment]
@SabaTD  
ხოდა რომ გამოგივა და მუშაობს, რაც არ გჭირდება უნდა წაშალო.

როგორ მიდის საქმეები, არის პროგრესული ძვრები ? :დ

**Comment by SabaTD** [comment]
ტყ პონტებიმაქვს, გამოცდები მქონდა 17 იანვრიდან  მოყოლებული 3  საგანში და ზეგ მაქ  მე-4  ოპერაციათა კვლევში კი გეცოდინება რა მურტალი რამეცაა დამტკიცებებს ვაკვდები რო ვისწავლო ზეპირად  ნახევარი მაინც -_-  .

 ახლა კოლეჯში ვარ და ახლა დავიწყებ შესწორებებს 3 საათი მაქვს თუ მოვასწარი დღესვე ავტვირთავ.  ახალ იდავალება გამოუშვი რა მანდამდე  ვიფიქრებ მაინც და რავი წინ წავიგდებ საქმეს.

**Comment by DavidDeme** [comment]
@SabaTD 
ახალი დავალება არ იქნება სანამ არსებულ დავალებაში შეცდომები არ გასწორდება.
ერთ-ერთი ფაილი რომელიც ჩაგისწორე, იმის მიხედვით შეცვალე სხვებიც.

**Comment by SabaTD** [comment]
გავაკეთე კაროჩე შევცვალე და წამოღება დამავიწყდა არ მაქვს კოლეჯში პროგრმა ასატვირთად და ხვალ ავტვირთავ.  მერე თარიღებს საათები, წუთები და წამები დავამატე და SELECT *FROM 'mylist' ORDER BY 'date'  გავაკეთე მაგრამ არშვებოდა რავიცი რაღაც პატარა შეცდომა მქონდა ზეპირად არ მახსოვს ერორი, ბოლოს გუგლით ვიჩალიჩე და გავასწორე ოღონდ mysql   გამოყენება მომიხდა, mysqli-ით არ გამოვიდა არაფრით.

**Comment by SabaTD** [comment]
ახალი დავალება მომეცი რა კაცურად, კოლეჯში რო მივალ ხვალ კაკრაზ დავიწყებ რას მაწვალებ. 
და პროექტია ჩასაბარებელი  ფოტოშოპში და ხატვა და აწყობა მერე იმ საიტის მინიმუმ 5 გვერდის ითხოვენ მარტამდე მაქვს დრო, რაზე გავაკეთო ისეთი რო მომვალშიც წამადგეს და პორტფოლიოშჳ შეტანა ღირდეს იმისი თან php-ც გამოვიყენო პრაკტიკის პონტში. მირჩიე რამე მოკლედ რა.

**Comment by DavidDeme** [comment]
@SabaTD 
პორტფოლიოს შეეშვი ჯერ, ამ ეტაპზე ისეთს ვერაფერს გააკეთებ რომ პორტფოლიოში შეიტანო, რომ მოგთხოვენ შენი აქაური გვერდის მისამართი მიეცი და კოდს ნახავენ, სლაიდებით რომ ააწყო და სურათები გადაუღო, ეგ ადრეა ჯერ :)
რაც შეეხება დავალებას, ამას პროსტა ზედაპირულად გადავხედე ამიტომ არ გამიშვია ჩემთან და ბოლომდე არ შემიმოწმებია თუმცა ერთი შეხედვით დამაკმაყოფილებელია. მაგრამ ახალი დავალება ისევ ამ პროექტთან იქნება დაკავშირებული, კერძოდ AJAX ტექნიკით შენი აპლიკაციის გაუმჯობესება:
1) გადახედე ამ კოდს http://www.w3schools.com/php/php_ajax_intro.asp
2) გამოიყენე ეს კოდი შენს აპლიკაციაში, კერძოდ: განახლების დროს, დამატების დროს და წაშლის დრო. ანუ მოქმედება უნდა მოხდეს იგივე გვერდზე, არ დაარეფრეშოს ბრაუზერი და აღარ უნდა დაგჭირდეს Updating.php-ს მგავსი გვერდების შექმნა იმისთვის რომ ინფორმაცია განაახლო, ამისთვის უნდა გამოიყენო AJAX და იმავე გვერდზე შეძლო განახლება.
3) ერთი შეხედვით რთული დავალებაა, მაგრამ რეალურად ძალიან მარტივია. ხო, აქედანვე როცა დაგუგლავ გაითვალისწინე რომ არ ჩაითვლება Jquery, ამიტომ გამოიყენე ზემოთ მოცემულ ლინკზე არსებული ინფორმაცია. 
4) შეგიძლია კოლეჯის ლექტორებიც დაიხმარო, მაგრამ Jquery არა იმენნო Javascript/Ajax მინდათქო ეგრე უთხარი ;დ
5) ვიცი მომავალშიც მომიწევს ახსნა და რატომ არ გჭირდება JQuery ამ ეტაპზე ახლავე მოგწერ ;დ. Jquery-ს იმპლემენტაცია არის ძალიან მარტივი, სადღაც 2-3 ხაზს დაწერ ან გადმოაკოპირებ იმიტომ რომ ყრია ყველგან და იმუშავებს, მაგრამ რეალურად AJAX რას შვება და როგორ, ეგ არ გეცოდინება. არადა სამომავლოდ რაღაც დავალება რომ შეასრულო AJAX თუ უფრო ღრმად არ გეცოდინება დაიტანჯები და იმ პატარა კოდშიც უფრო დაიბნევი იმიტომ რომ გაგიჭირდება კოდში ის აზრი დააფიქსირო რასაც რეალურად ფიქრობ. პირდაპირ JavaScript-ს როცა გამოიყენებ, გაიაზრებ თითოეული ხაზი რისთვის გჭირდება, თუ დაწერ ეი შედარებით უფრო მეტად გეცოდინება AJAX ვიდრე Jquery-ს შემთხვევაში რადგან learning curve (შესწავლის დრო) გაცილებით მეტი სჭირდება და საჩკაობით ვერ დაამუღამებ. ხოდა საბოლოოდ უფრო მოგებული დარჩები, ამის ცოდნით Jquery-საც შეჭამ და ისიც გეცოდინება საიდან მოდის და რატომ. თუმცა შემიძლია გითხრა რომ Jquery-ს აღარ მიუბრუნდები როცა ორივეს დააგემოვნებ რაღაც დონეზე ;დ ენივეი, ჯერ ადრეა ამაზე, ჩაუჯექი და იწვალე

**Comment by DavidDeme** [comment]
@SabaTD 
http://stackoverflow.com/questions/30414372/ajax-post-implementation-in-pure-javascript/30414515#30414515 -> ამ ბმულზე არის ჩემი დაწერილი პასუხი, შეგიძლია ზუსტად ეს გამოიყენო ამ დავალების შესასრულებლად. ახსნილიც მაქვს და რავი, დაღეჭილი ფაქტიურად. მეტს ნაღდად არ დაგეხმარები ;დ

**Comment by SabaTD** [comment]
კარგი გასაგებია, დღეს უსაქმურად ვიყავი დილის 9 დან და რესპონსივი გავხადე მთლიანი კოდი მშვენიერი გამოვიდა :) მივხედამ ახლა ამ  AJAX თუმცაღა ლექტორმა არ იცის და მომიწევს გუგლში ძრომიალი ყოველ პატარა დაბრკოლებაზე.

და ჯიქუერიზე კი ვიცი ეგ რო ძალიან ამოკელბს ჯავასკრიპტს და ეგ მომწონს ასე თუ ისე :დ
სურათების სლაიდერი კი მაქ გაკეთებული ჯავასკრიპტითაც და ჯიქუერითაც :პ

**Comment by DavidDeme** [comment]
@SabaTD 

არანაირი JQuery, იმიტომ მოგწონს რომ მარტივი გამოსავალი გგონია, არადა პირიქით, როცა რთულ დავალებებს გააკეთებ ბევრად უფრო გაგიჭირდება იმ მხრივ რომ საბაზისო ცოდნა არ გექნება ჯავასკრიპტის და ასმაგი წვალება მოგიწევს.
მოკლედ, JQuery-თ დაწერილი კოდი არ ჩაითვლება, გასაგებად აგიხსენი მგონი ;დ

ეგ უნდა გამოიყენო მაქსიმუმ დიზაინის მხარეს როცა გინდა კარგი ეფექტის მიღება და მაგ დროს შეგიძლია დაიკიდო სისწრაფე. როცა მონაცემებს ცვლი და მნიშვნელოვან ინფორმაციას და 35-ჯერ უფრო ნელია სისულელეა მაგის გამოყენება, პროსტა ინტერნეტში 90% მაგის კოდები დევს და პაპსაა, მე პროსტა თავიდანვე არ გამისწორდა რომ რასაც ვწერდი იმ 2-3 ხაზში არ მესმოდა და ვერ ვხვდებოდი რისთვის იყო საჭირო. მაგიტომ თავიდანვე რთული გზით წავედი და ბევრად უფრო მშვიდად ვგრძნობდი თავს როცა ვიცოდი სად, რა უნდა დამეწერა და კაი პონტია ზოგადად  ინტერნეტიდან რომ არ აკოპირებ ყველაფერს და შენითაც ჩალიჩობ, დამოუკიდებლად ;დ
მერე 1-2 წელი რომ მოიხოდები, თუ დაგჭირდება უპრობლემოდ გამოიყენებ, მაგრამ აღარც მოგინდება. მაქსიმუმ დიზაინზე სლაიდი, ეფექტები და ეგეთი აპლიკაციის გამართული მუშაობისთვის შედარებით ნაკლებად მნიშვნელოვანი საკითხებისთვის.

სამსახურისთვისაც, ბევრად უფრო კაი პონტად ჩაგეთვლება მაგას რომ ეტყვი, იმიტომ რომ 90% Jquery-ს უბერავს და რეალურად ჯავასკრიპტის განვითარების პონტში, მილიონი Jquery-ს მსგავსი ბიბლიოთეკა არსებობს და ბევრი აღარც იყენებს. ხოდა კამანდამ რომ ბიბლიოთეკა იცის და მის უკან რაც დგას ის არა, ვერაა მომგებიანი. საბაზისო რომ იცი 1000 ბიბლიოთეკას დაამუღამებ და პირიქით, ბევრად უფრო რთულია.

ანუ, ყველაფერი კარგია და ყველაფერი უნდა იცოდე. მაგრამ საწყის ეტაპზე რომ ეფექტურად აითვისო და არ გაგეწელოს, ამ ეტაპზე უარი უნდა თქვა JQuery-ზე. მაგას მერე შენით აითვისებ 1-2 წლის მერე, უმტკივნეულოდ და წვალების გარეშე :დ

**Comment by SabaTD** [comment]
მოკლედ გუშინ გადავხედე და დღესაც ვუზივარ შენ კოდში იდეა გასაგებია რასაც აკეთებ, 
იდაში მხოლოდ  შენ რომ გიწერია server.php ანუ ჩემს შემთხვევაში updating.php -ის შეცვლა მიწევს, ისე უნდა გავაკეთო რომ ჯერ ტექსტზე რედაქტირების უფლება მომცეს და მერე update  ღილაკზე დაჭერის დროს შეინახოს. ანუ ამ ღილაკს onclick-ზე ფუნქციას რომ მივცემ მანდ გააქტიურდება AJAX და რეფრეშის გარეშე გამოიტანს შეცვლილ კოდს ოღონდ ეს შეცვლილი კოდის გაგზავნა php-ით უნდა გაკეთდეს შენ რომ გაქვს alert-ს რომ აკეთებს მაგის მაგივრად.
სწორს ვიძახი ?  ტექსტის რედაქტირების უფლება როგორ მივიღო ?  სხვა ღილაკის გაკეთება მომიწევს მაგისთვის თუ სხვა გზაც არის  ?   მაგალითად იყოს ღლაკი სახელად update და ამ update-ს რო დააჭერ ის გაქრეს და გაგზავნა გამოჩნდეს მაგის ადგილას?

**Comment by DavidDeme** [comment]
@SabaTD 
პროცესი უნდა იყოს ზუსტად ისეთი როგორიც აქაა, როცა არსებული კომენტარის განახლება გინდა
1) აჭერ განახლების ღილაკს http://prntscr.com/9uxy0w
2) კომენტარის ტექსტი უკვე ხდება განახლებადი, ანუ მისი შეცვლა შეგიძლია http://prntscr.com/9uxyad
3) აჭერ Update Comment და იქვე იცვლება.
ეს ხდება გვერდის დაურეფრეშებლად, ანუ ბექგრაუნდში და მომხარებელი არ გადადის იმ ლინკებზე/რესურსებზე რომლებიც ამ პროცესში მონაწილეობენ

**Comment by DavidDeme** [comment]
@SabaTD 
ახლა როგორ ხდება ეს დაახლოებით რომ ავხსნათ
1) განახლების ღილაკზე მიბმულია ამ ჩანაწერის ID
2) როდესაც კლიკავ, ეშვება ფუნქცია რომელიც ჯავასკრიპტის დახმარებით ცვლის კომენტარის ვიზუალს და აქცევს მას რედაქტირებად, input/textarea ელემენტად, რომელსაც ქვემოთ ემატება ორი ღილაკი გაგზავნა/უარის თქმა.
3) გაგზავნის ღილაკს ქმნის წინა ფუნქცია, რომელსაც უკვე აქვს ID. როცა წინა ფუნქცია ქმნის გაგზავნის ღილაკს, თავისი onclick ფუნქციით, გადასცემს იმ ID-ს რომელიც თვითონ აქვს. შესაბამისად, onclick მოვლენის დროს შენ იცი რომელი კომენტარი უნდა განახლდეს, რადგან როგორც ზემოთ გითხარი წინა ფუნქციამ უკვე იზრუნა და გადმოსცა ახალ ფუნქციას მისი შექმნის პროცესში ის ID. 
4) ამას ყველაფერს შენით აკეთებ, არაფერი სასწაული არ ხდება. წარმოიდგინე რომ ის კომენტარი არის DIV, რომელსაც აქვს რაღაც ID. როცა კლიკავ განახლებას, ეშვება ფუნქცია რომელიც ამ დივს ძებნის მისი ID-თ. მერე ამ დივს უკვე ამუშავებ ჯავასკრიპტის DOM API-თ და თუ ცოტას დასერჩავ მიხვდები რომ მისი დამუშავება მარტივად შეიძლება, ანუ ზუსტად ისე როგორც ამ გვერდზეა კომენტარების შემთხვევაში
5) როცა დააჭერ გაგზავნას, განახლების გვერდისკენ აგზავნი ID-ს რომ მიხვდეს რას ანახლებს და ჩანაწერებს. 
6) ის გვერდი ანახლებს და განახლებულს გიგზავნის, რომელსაც შენ ისევ და ისევ ჯავასკრიპტით უმატებ არსებულ გვერდს და იღებ უახლეს ინფორმაციას. ეს ყველაფერი კიდევ ერთხელ რომ გავიმეოროთ ხდება ბექგრაუნდში

**Comment by DavidDeme** [comment]
@SabaTD 
მოკლედ ამას ახლა ერთ და ორ დღეში ვერ გააკეთებ, ნუ შეიძლება გააკეთო მაგრამ დრო გინდა ნებისმიერ შემთხვევაში. ამიტომ დასერჩე, ივარჯიშე და ნელ-ნელა მიდი იმ დონემდე რომ უკვე ეს ყველაფერი გააკეთო აპლიკაციის დონეზე. მე შენს ადგილზე ასე დავყოფდი საკითხებს.
1) AJAX მოთხოვნის გაგზავნა რაღაც გვერდისკენ, პასუხის მიღება და alert-ში გამოტანა გვერდის დაურეფრეშებლად
2) DOM-ს გამოყენებით ელემენტების მოძებნა და მათი ცვლილება, გადაკეთება.
3) DOM-ს გამოყენებით ელემენტის ინფორმაციის ცვლილება, ანუ ტექსტის.
4) ზედა სამის გამოყენება აპლიკაციაში

**Comment by SabaTD** [comment]
Thank You

**Comment by DavidDeme** [comment]
@SabaTD 

რა ხდება, როგორ მიდის საქმეები, არ მოდუნდე და დროულად დაამუღამე, კვირის ბოლომდე ველოდები საწყის კოდს ;დ

**Comment by SabaTD** [comment]
ავტვირთე ისევ იქ, ახლა მაინც შეხედე -_- 

footerform.php   და edit.php ნახე.

**Comment by DavidDeme** [comment]
@SabaTD 

კოლაბორატორებში ჩამამატე Setting-დან.

**Comment by SabaTD** [comment]
Done

**Comment by DavidDeme** [comment]
@SabaTD

და კიდევ ერთი.
phpmyadmin-ში ბაზა შეგიძლია დააექსპორტო რომ სხვამაც გამოიყენოს.
ამიტომ თითოეულ პროექტზე დააექსპორტე ბაზა და ის ფაილი, DB ფოლდერში შეინახე.
მაგალითად ToDoList -> DB ფოლდერში გექნება ახლა ამ პროექტის ბაზის ფაილი რომ მერე ჩემთანაც გავუშვა შენი აპლიკაცია და შეცდომები მოვძებნო. 
გამოასწორე ეგეც და დავიწყოთ მერე შეცდომების გასწორებაც :)

**Comment by SabaTD** [comment]
ეგეც გავაკეთე, ნახე აბა.

**Comment by DavidDeme** [comment]
@SabaTD 

ვსიო, კაია.
მსგავსი სტილით ატვირთე ახალი პროექტები ხოლმე, რომ მეც გადავამოწმო.
გადავხედავ მოგვიანებით და მოგწერ ხვალ დღის ბოლომდე..

**Comment by SabaTD** [comment]
ოკს, რეგისტრაციის ფორმაზე წავიმეცადინებ მაშინ იქნება მანდაც დავწერო რამე :დ

**Comment by DavidDeme** [comment]
@SabaTD ჰე რა ხდება, რას ველოდებით ;დ

**Comment by SabaTD** [comment]
მოკლედ ბატონო დემე რეგისტრაცია და ლოგინი გავაკეთე ყველაფერი მშვენივრად, ერთი ბაზაში თუ არსებობს ის უსერნეიმი ეგ რო აღარ დაამატოს არ გამიკეთებია.  

StoreHouse -ს რაც შეეხება ლექტორმა მომცა დავალება პირადად კოლეჯში საწყობში გასაყიდი საქონლის შეტანა გატანის აღრიცხვას აწარმოებ მოკლედ სადაც არის 2 ძირითადი გვერდი 1 საქონლის ბაზაში შეტანის, და მეორე გამყიდველის ფეიჯი საიდანაც გაყიდვის დროს ბაზიდან ავტომატურად იშლება.

და Contact_Gallery ჯგუფელთან ერთად დავწერე,  თავის ნაცნბს უწყობდა გვერდს და მოკლედ მანდ ქონტაქტი და გალერიაა ჩემი რა მარტო, სურათების დამატება სლაიდერში და საკონტაქტო ინფორმაციის შეცვლა.

ველოდები შენიშვნებს, თქვენგან განსხვავებით მე არ ვზარმაცობ ;)

**Comment by DavidDeme** [comment]
@SabaTD 
პირველი შენიშვნა:
ნებისმიერ აპლიკაციას უნდა ჰქონდეს საწყისი წერტილი. ანდროიდზე დაწერ მობაილ აპლიკაციას, ვებ აპლიკაციას დაწერ თუ დესკტოპ აპლიკაციას, რა ენაზეც და პლატფორმაზეც არ უნდა წერდე, ყველას გააჩნია ეგ საწყისი წერტილი, რომელიც by default არის განსაზღვრული და ყველა იყენებს.
PHP-ს შემთხვევაში, ცოტა მოგვიანებით როცა დაამუღამებ და გეცოდინება სერვერის კონფიგურირება შენით დააყენებ, მაგრამ იქამდე სასურველი და რეკომენდირებულია, პლიუს განსაზღვრული რომ პროექტის საწყისი ფაილი იყოს index.html ან index.php (მე მეორეს გირჩევ), რაც ნიშნავს იმას რომ ბრაუზერიდან შენი პროექტის გახსნისას -> localhost/project, პირველ რიგში გაიხსნება ეგ ფაილი და იქნება საწყისი წერტილი.
ხოდა შენს ფოლდერებში რომ შევდივარ და გარჩევა მინდა, რეალურად მარჩიელობა მიწევს რომ მივხდე სად რა ხდება და როგორ ;დ ამიტომ ეგ გამოასწორე პირველ რიგში :)

**Comment by SabaTD** [comment]
გავითვალისწინებ, ახლა ნუ მასწორებინებ სათითაოდ პროექტებზე სახელებს.

 ნახე რამე  კოდში ან გაუშვი ?

**Comment by DavidDeme** [comment]
@SabaTD 

გაასწორე, შენთვისვე უკეთესია :)
ვინმემ რომ ჩაიხედოს შიგნით გული შეუწუხდება და ჯობია აქედანვე მიეჩვიო სწორ წერას ;დ
